name: lh-ed-maksuel-nascimento

networks:
  database:
    name: meltano-database
  airflow:
    name: meltano-airflow

services:
  scheduler:
    build:
      context: .
      target: scheduler
    image: meltano:airflow-scheduler
    container_name: indiciumtech-meltano-scheduler
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - airflow
      - database
    ports:
      - 8793:8793

  webserver:
    build:
      context: .
      target: webserver
    image: meltano:airflow-webserver
    container_name: indiciumtech-meltano-webserver
    restart: unless-stopped
    depends_on:
      - scheduler
    networks:
      - airflow
      - database
    ports:
      - 8080:8080

  db:
    image: postgres:12
    container_name: indiciumtech-postgres
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    networks:
      - database
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432